seed: 42
weight_dtype: bf16
stage_init: True
max_pose_len: 500
codebook_size: 625
pose_size: 64
p_keep: 0.6

modules:
  text_model: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
  ckpt: 
  embed_dim: 512
  clip_dim: 512
  block_size: 501
  num_layers: 8
  head_layers: 1
  n_head: 8
  drop_out_rate: 0.1
  fc_rate: 4
  codebook_size: 625
  attn_type: "local:128"
  head_type: default

gradient_checkpointing: False

solver:
  max_train_steps: 50000
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer:
    use_8bit_adam: True
    learning_rate: 2e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 1.0e-6
    adam_epsilon: 1.0e-8
  lr_scheduler:
    name: "cosine"
    lr_warmup_steps: 200

dataset:
  frame_size: [ 512, 512 ]
  frame_scale: [ 1.0, 1.0 ]
  frame_ratio: [ 0.9, 1.0 ]
  roots:
    - "/deepo_data/signvipworkspace/datasets/How2Sign"
  sk_roots: 
  hamer_roots:
  pose_roots: 
    - /deepo_data/signvipworkspace/datasets/RWTHCompressVQPose/20250105-0626-FSQ625
  meta_paths:
    - "/deepo_data/signvipworkspace/datasets/RWTH-T/train_processed_videos.json"
  sample_rate: 1
  num_frames: 1
  ref_margin: 5
  uncond_ratio: 1
  mask_ratio: 0
  mask_thershold: 0.85
  skip_ratio: 0

dataloader:
  batch_size: 16
  num_workers: 4

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  steps_offset: 1
  clip_sample: false

resume_from_checkpoint: 
checkpointing_steps: 2000
valid_steps: 2000
max_ckpt: 1
max_model: 1

noise_offset: 0
clip_skip: 1
snr_gamma: 0

max_visible_frames: 6
max_sin_pe_len: 1000

validation_data:
  meta_paths:
    - "/deepo_data/signvipworkspace/datasets/RWTH-T/dev_processed_videos.json"
