seed: 42
weight_dtype: fp16
stage_init: true
pose_aug_rate: 0.001
modules:
  vae: /deepo_data/signvipworkspace/models/sd-vae-ft-mse
  unet_2d: /deepo_data/signvipworkspace/models/stable-diffusion-v1-5/unet/
  text_encoder: /deepo_data/signvipworkspace/models/stable-diffusion-v1-5/text_encoder/
  tokenizer: /deepo_data/signvipworkspace/models/stable-diffusion-v1-5/tokenizer/
  scheduler: /deepo_data/signvipworkspace/models/stable-diffusion-v1-5/scheduler/
  apperance_encoder: /deepo_data/signvip/workspace/stage_1_multicond_RWTH/20250205-0513/best/appearance_encoder
  condition_encoder: /deepo_data/signvip/workspace/stage_1_multicond_RWTH/20250205-0513/best/condition_encoder/model.bin
  mm: /deepo_data/signvipworkspace/models/mm_sd_v15_v2.ckpt
  unet: 
  mid_channels: 8
  unet_additional_kwargs:
    use_motion_module: true
    motion_module_resolutions:
    - 1
    - 2
    - 4
    - 8
    unet_use_cross_frame_attention: false
    unet_use_temporal_attention: false
    motion_module_type: Vanilla
    motion_module_kwargs:
      num_attention_heads: 8
      num_transformer_block: 1
      attention_block_types:
      - Temporal_Self
      - Temporal_Self
      temporal_position_encoding: true
      temporal_position_encoding_max_len: 32
      temporal_attention_dim_div: 1
      zero_initialize: true
grad:
  vae: false
  unet_2d: false
  appearance_encoder: false
  text_encoder: false
  condition_encoder: false
trainable_modules:
- motion_modules.
- compress_layer.
- decompress_layer.

gradient_checkpointing: false
solver:
  max_train_steps: 50000
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer:
    use_8bit_adam: true
    learning_rate: 1.0e-05
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: 1.0e-08
  lr_scheduler:
    name: constant
    lr_warmup_steps: 1000
dataset:
  frame_size:
  - 272
  - 224
  frame_scale:
  - 1.0
  - 1.0
  frame_ratio:
  - 0.9
  - 1.0
  roots:
  - /deepo_data/signvipworkspace/datasets/RWTH-T
  sk_roots:
  - /deepo_data/signvipworkspace/datasets/RWTH-TSK
  hamer_roots:
  - /deepo_data/signvipworkspace/datasets/RWTH-TSmplerx
  meta_paths:
  - /deepo_data/signvipworkspace/datasets/RWTH-T/train_processed_videos.json
  sample_rate: 1
  num_frames: 16
  ref_margin: 5
  uncond_ratio: 1
  mask_ratio: 0
  mask_thershold: 0.85
  skip_ratio: 0
  sk_mask_ratio: 0
  hamer_mask_ratio: 0
  both_mask_ratio: 0

dataloader:
  batch_size: 2
  num_workers: 4
noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: linear
  steps_offset: 1
  clip_sample: false
resume_from_checkpoint: 
checkpointing_steps: 2000
valid_steps: 2000
max_ckpt: 1
max_model: 1
noise_offset: 0
clip_skip: 1
snr_gamma: 5.0
max_visible_frames: 6
validation_data:
  meta_paths:
    - "/deepo_data/signvipworkspace/datasets/RWTH-T/dev_processed_videos.json"
  prompt: ''
  num_inference_steps: 20
  guidance_scale: 3.5